### ISSUE TITLE
fbp & fbc cookies should be generated

### ISSUE THREAD

**Issue by ajtatum** [stape-io/facebook-tag#10]
I saw in issue #2 that this was closed, but I believe these cookies should be set. Instead, I get a FPID, FPID2, and FPLC cookie and when making a request to Facebook it looks for "very_important_cookies" which are fbp and fbc... which would obviously be null since this template doesn't set those values.

**Comment by Bukashk0zzz** [comment]
This template use and set cookies according to FB documentation.
Please check https://github.com/stape-io/facebook-tag/blob/main/template.tpl#L434
And https://developers.facebook.com/docs/marketing-api/conversions-api/parameters/customer-information-parameters#fbc

_fbp - can be generated only if you use Web FB pixel besides server tag. And _fbc in cases users come from FB pages/ads.
Look like you have issues with the setup of GTM SS itself that are not related to this tag.
