### ISSUE TITLE
content_ids missing?

### ISSUE THREAD

**Issue by JannikZed** [stape-io/facebook-tag#13]
Hi there,
I just came across an issue in our integration using the tag manager server container. It seems like your tag is not setting the "content_ids", but just the "contents" array when interacting with a product in our shop. Are we missing a parameter in our GA4 integration?
![Screenshot 2021-12-04 at 14 25 09](https://user-images.githubusercontent.com/7526174/144711180-adffa9da-fad2-4212-be41-a1192bb3d72f.png)

Seems like the content_ids needs to be an array of all product_ids that are already in the contents array.. I don't know, why Facebook needs this information twice, but I can see for example in the Facebook commerce manager, that it can't match any event from our page with our product data feed, because it seems to use just the content_ids array for that.

**Comment by Bukashk0zzz** [comment]
You are correct this tag setting automatically only contents. And we don't have any issues with this before. Also how I understand FB documentation you can use contents or content_ids.

More info: https://developers.facebook.com/docs/facebook-pixel/reference

<img width="855" alt="Screenshot 2021-12-07 at 18 42 43" src="https://user-images.githubusercontent.com/1908342/145070235-e2bba194-e446-4e62-a1b0-0312f5cc1e42.png">


In any way, this tag supports sending any parameters to Facebook. So you can set content_ids explicitly inside the tag. 

<img width="995" alt="Screenshot 2021-12-07 at 18 49 09" src="https://user-images.githubusercontent.com/1908342/145071258-10569cf6-213f-4498-a0e1-9a36b454014b.png">

**Comment by khanhicetea** [comment]
Hi,

`content_ids` is required when you send `content_type = product_group` (in case view_item - ViewContent, because the user view the whole product instead 1 its variant).

So it should be better we can generate `content_ids` from `items` when `content_type = product_group`

At the moment I have to create 2 tags with 2 triggers (1 for view_item , 1 for the rest cases)

Btw, thank you for the template :)

**Comment by khanhicetea** [comment]
@Bukashk0zzz ohh now I confirmed your link reference is more clarity than the first picture of document (it doesn't mention about using **product group IDs** in `contents`, so many people misunderstood 

![image](https://user-images.githubusercontent.com/4528223/166727732-9528b8d1-7e48-4e31-b212-43ba3114498f.png)

So thank you for clarifying with another official docs link from Meta
