### ISSUE TITLE
Server Sending Invalid Match Key Parameters for PageView Event

### ISSUE THREAD

**Issue by JannikZed** [stape-io/facebook-tag#14]
The Facebook event manager gives me this error now:

![Screenshot 2021-12-17 at 14 18 50](https://user-images.githubusercontent.com/7526174/146550854-bda3343e-843b-473b-b5bc-f8a08410621f.png)

**Comment by Bukashk0zzz** [comment]
Can you please send logs from the console tab? What IP and fbc are in Event Data?
