### ISSUE TITLE
Ecommerce data: change content-type

### ISSUE THREAD

**Issue by bashoogzaad** [stape-io/facebook-tag#18]
Hi there!

Thanks for this great library! I was wondering if I can change the content_type for the e-commerce data in this tag. I need to set it to 'product_group' and not 'product'. I see that I can change this in the code, however it is maybe better to create some extra setting for this. With an update, this code would be removed.

Kind regards,

Bas

**Comment by Bukashk0zzz** [comment]
Hi,

Thanks for the feedback. You can already do this.
<img width="1233" alt="Screenshot 2022-03-30 at 12 15 39" src="https://user-images.githubusercontent.com/1908342/160796909-d2c2bac3-3850-4783-ac86-64a2672b9181.png">

**Comment by bashoogzaad** [comment]
thank you!
