### ISSUE TITLE
Email should be able to be fetched according to Google Ads Enhanced Conversions setup

### ISSUE THREAD

**Issue by sorendam** [stape-io/facebook-tag#19]
Currently, the code says: `else if (eventData.user_data && eventData.user_data.email_address) mappedData.user_data.em = eventData.user_data.email_address;`. In the docuementation for Google Ads https://support.google.com/google-ads/answer/10172785 the email address uses 'email' instead of 'email_address'. It would be nice if the tag could support this.

**Comment by Bukashk0zzz** [comment]
Thanks for the feedback. Done https://github.com/stape-io/facebook-tag/commit/929203274f1a6a24c5d9d15cd6b6894962b24129
