### ISSUE TITLE
city in incorrect format

### ISSUE THREAD

**Issue by sorendam** [stape-io/facebook-tag#20]
According to Facebook docs city (ct) should be without spaces. E.g. 'menlo park' should be 'menlopark'. See https://developers.facebook.com/docs/marketing-api/conversions-api/payload-helper/

Also, it would be nice if it could strip a + sign from the phone number if present. And if country code was not provided, then it could look that up from the country submitted.

**Comment by Bukashk0zzz** [comment]
Thanks for the feedback. Done https://github.com/stape-io/facebook-tag/commit/929203274f1a6a24c5d9d15cd6b6894962b24129

> And if country code was not provided, then it could look that up from the country submitted.
Require too much code for sGTM template.
