### ISSUE TITLE
eventData._fbc & eventData._fbp

### ISSUE THREAD

**Issue by Kixell-NicolasJardillier** [stape-io/facebook-tag#22]
Hi,

is this code wrong ? 
```
if (!fbc) fbc = eventData._fbc;
if (!fbp) fbp = eventData._fbp;
```
In fact it is not possible to set fields with a name starting with an underscore in the tag GA4 of the GTM Web

Best regards

**Comment by Bukashk0zzz** [comment]
Hi,

It is not wrong. This is for use cases when you send events from not GA4, for example, thru webhook.
If you use GA4 tag/client _fbp and _fbc cookies will be send to server automatically.

**Comment by Kixell-NicolasJardillier** [comment]
Hi, but the code mentioned is related to Event Data not the cookie.
Code related to the cookie is above in the code

**Comment by Bukashk0zzz** [comment]
Exactly. Code lines 34 and 35 for cases when you send data from server to server integration, and there will be no cookies.

What issue do you have, and what are you trying to achieve?

**Comment by Kixell-NicolasJardillier** [comment]
I understand, it is clear for me now
