### ISSUE TITLE
Facebook: Server Sending Invalid Match Key Parameters for CompleteRegistration Event

### ISSUE THREAD

**Issue by ahmedmaazin** [stape-io/facebook-tag#23]
Similar to: https://github.com/stape-io/facebook-tag/issues/14

I am getting the following error: (**Server Sending Invalid Match Key Parameters for CompleteRegistration Event**)
<img width="1250" alt="Screenshot 2022-10-13 at 12 27 20" src="https://user-images.githubusercontent.com/4073159/195573042-1cf2fd7b-bb5e-4809-bdf5-ac6f3fb2e781.png">

**Console tab logs:**
<img width="927" alt="Screenshot 2022-10-13 at 12 40 43" src="https://user-images.githubusercontent.com/4073159/195582547-e9d6b38d-a27a-4bb1-ab72-8f71120e6f30.png">

<img width="326" alt="Screenshot 2022-10-13 at 12 44 43" src="https://user-images.githubusercontent.com/4073159/195582330-7ecfc708-5b6e-439c-ae6e-a573a6f369ca.png">

_Note: Let me know if the above details are enough to help me figure out to point the issue & thank you in advance :)_

**Comment by Bukashk0zzz** [comment]
I don't see any issues with this request. 
Did you use FB pixel + CAPI or only CAPI?

The issue might be in case WEB FB Pixel send one FBP and Server send other FBP. Did you check that web and server send same FBP?

**Comment by ahmedmaazin** [comment]
> 
Using only **CAPI** I believe:
<img width="438" alt="Screenshot 2022-10-14 at 11 56 27" src="https://user-images.githubusercontent.com/4073159/195819212-c4ebccb1-198a-46cb-9559-66e801a7aa48.png">

a) Should both (browser web and server) send the **_fbp** or only the server should?

In any case, I'm checking if both are sent and if both are the same or different. I'm guessing if it does, it should be the same.

Will keep you posted with new findings :)

**Comment by ahmedmaazin** [comment]
_Update:_

I just found out that **_fbp** is different from web vs server. Think might be an issue 🤔

**Comment by Bukashk0zzz** [comment]
Both should have a same _fbp. Did you use custom domain?

**Comment by ahmedmaazin** [comment]
> Both should have a same _fbp. Did you use custom domain?

Oh yes I do 💭

**Comment by ahmedmaazin** [comment]
**Quick update:** I mentioned earlier that I've verified that both send the same `_fbq`, but still it's popping up in Facebook Diagnosis :( Is there anything you think I might have missed or ideas on where I could look into further? Otherwise, I can close this issue :)

**Comment by Bukashk0zzz** [comment]
Sorry no any new ideas.
