### ISSUE TITLE
content_category Hierarchy Missing

### ISSUE THREAD

**Issue by yoraysa** [stape-io/facebook-tag#37]
Hi,
Sub categories seem to be missing in the outgoing request.
Theoretically this means that all **sub categories** won't be available via the content_category parameter.

see sGTM vs. Facebook's "test events":

<img src="https://github.com/stape-io/facebook-tag/assets/9439146/363724c4-137e-45c4-b147-10a407f34eeb" width="300">
<br />
<br />
<br />

the value should be **Apparel > Adult > Shirts > Crew > Short sleeve**

https://developers.facebook.com/docs/meta-pixel/advanced/
<img src="https://github.com/stape-io/facebook-tag/assets/9439146/7a363cb2-6d86-4f9f-98fe-3d7e0d4122be" width="300">

**Comment by Bukashk0zzz** [comment]
Hi,

Not sure we can help you.
Basically, you define the category that you send to FB.
So, if you want to send another category then send it.

**Comment by yoraysa** [comment]
for "single product" events such as viewcontent & addtocart you want to have this structure of **main cat > sub cat > sub sub cat_** based on the the item_categoryN parameters received by the sgtm ga4 client.

in my example, I'm sending 5 different categories... just wanted to point this out as it seems like the correct practice

**Comment by kHorozhanov** [comment]
Hi @yoraysa!
We discussed your request and decided to leave this functionality as is.
You can override the category value to pass some custom structure.
Thanks for your request!
